### PR TITLE
Fix adding user to user_groups_users

### PR DESCRIPTION
**Pull request by ahmgeek**
Using include somtimes gives false positive values, hence replacing it
with exists

### CODE REVIEW

**Comment by tobithiel** [comment]
Can you give me a bit more information on when or why that happens?
Calling exist with a `ActiveRecord::Base` class seems to be deprecated according to the code listing here: http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-exists-3F

**Comment by ahmgeek** [comment]
Well, I've overridden the `Strongbolt::UserGroup` controller in Active admin, in the create action I've implemented the same actions as the strongbolt controller did, that's because I wanted to override the whole views and re implement it in ActiveAdmin with a little customization.
the create action have this:
` @user_group.users << @user unless @user_group.users.include?(@user)`
include actually didn't work with me.
also this didn't work :
```
      @user_group = Strongbolt::UserGroup.find params[:id]
      # We select the users not yet in the user group
      @users = Strongbolt.user_class_constant
        .joins("LEFT JOIN strongbolt_user_groups_users sugu ON sugu.user_id = #{Strongbolt.user_class_constant.table_name}.id")
        .joins("LEFT JOIN strongbolt_user_groups sug ON sug.id = sugu.user_group_id")
        .where("sug.id IS NULL OR sug.id != ?", @user_group.id)

```

**Comment by tobithiel** [comment]
What does `didn't work` mean? Is there an exception?

**Comment by ahmgeek** [comment]
No I meant the population of the array was having the users that been already assigned to that group.
I meant by `didn't work` the behavior.

**Comment by tobithiel** [comment]
As far as I can tell `include?` basically calls `exists?` internally, but also deals with some association specific logic. I don't think this will fix the problem.
The current code could definitely lead to a race condition where a user ends up in the group twice. We should add an unique index to the table to prevent that, that's the only way to actually enforce this according to the [Rails documentation](http://guides.rubyonrails.org/association_basics.html).
I'll leave this open to remind me this still needs to be done, but will do it with a unique index on the table.
Thanks for reporting this!

**Comment by tobithiel** [comment]
I just published a new version `0.3.9` which includes a new unique index for group memberships, so that they are actually enforced.
It will be included in new installation by default when running `rails g strongbolt:install`. For your existing installation run `rails g strongbolt:fix_unique_group_members` once to create the new migration.
Let me know if you run into any problems.

**Comment by ahmgeek** [comment]
:kissing_heart:

**Pull request closed without merging**
